In [8]:
import numpy as np
import pandas as pd

print("Libraries loaded")

Libraries loaded

In [9]:
df= pd.read_csv(r"C:\Users\Admin\OneDrive\Desktop\ML_OPS_FRAUD_DETECTION_project 3\data\creditcard.csv")

In [10]:
df.shape

(284807, 31)

In [11]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [13]:
df.columns.tolist()

['Time',
 'V1',
 'V2',
 'V3',
 'V4',
 'V5',
 'V6',
 'V7',
 'V8',
 'V9',
 'V10',
 'V11',
 'V12',
 'V13',
 'V14',
 'V15',
 'V16',
 'V17',
 'V18',
 'V19',
 'V20',
 'V21',
 'V22',
 'V23',
 'V24',
 'V25',
 'V26',
 'V27',
 'V28',
 'Amount',
 'Class']

In [14]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [15]:
fraud_percent=df["Class"].mean()*100                  
print(f"Fraud percentage in dataset: {fraud_percent:.3f} %")
# using mean() w/o specifying label class=='1'cz column class is binary so will not count 0 while calculating

Fraud percentage in dataset: 0.173 %

The dataset is highly imbalanced with fraud taking only o.173 % so only acccuracy alone is not enough to evaluate our fraud detection models.

In [16]:
#Missing values
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [17]:
#duplicate values
df.duplicated().sum()

np.int64(1081)

In [18]:
#dataset statistics
df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.175161e-15,3.384974e-16,-1.379537e-15,2.094852e-15,1.021879e-15,1.494498e-15,-5.620335e-16,1.149614e-16,-2.414189e-15,...,1.628620e-16,-3.576577e-16,2.618565e-16,4.473914e-15,5.109395e-16,1.686100e-15,-3.661401e-16,-1.227452e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [19]:
#transaction amount
df['Amount'].describe()

count    284807.000000
mean         88.349619
std         250.120109
min           0.000000
25%           5.600000
50%          22.000000
75%          77.165000
max       25691.160000
Name: Amount, dtype: float64

In [20]:
# seperate features from output
X=df.drop('Class',axis=1)
y=df['Class']
print(X.shape)
print(y.shape)

(284807, 30)
(284807,)

In [21]:
#train and test split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,                                        
    stratify=y)

#using stratify to ensure train/test have same fraud proprtion as our dataset

In [19]:
print("Training:", X_train.shape)
print("\nTesting:", X_test.shape)



print("\nTraining target:")
print(y_train.value_counts())

print("\nTesting target:")
print(y_test.value_counts())

Training: (227845, 30)

Testing: (56962, 30)

Training target:
Class
0    227451
1       394
Name: count, dtype: int64

Testing target:
Class
0    56864
1       98
Name: count, dtype: int64

In [20]:
#Train Logistic Regression
from sklearn.linear_model import LogisticRegression

LR_model=LogisticRegression(class_weight="balanced",max_iter=1000,random_state=42)
LR_model.fit(X_train,y_train)

C:\Users\Admin\OneDrive\Desktop\ML_OPS_FRAUD_DETECTION_project 3\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [21]:
#Logistic Regresssion prediction andprobabilities
LR_prediction=LR_model.predict(X_test)
LR_Probabilites=LR_model.predict_proba(X_test)[:, 1]

In [22]:
#Train Random Forest 
from sklearn.ensemble import RandomForestClassifier

RF_model=RandomForestClassifier( n_estimators=100,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1)
RF_model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42)

In [23]:
RF_prediction= RF_model.predict(X_test)
RF_probabilities = RF_model.predict_proba(X_test)[:, 1]

In [24]:
#Train XGboost
import xgboost as xgb
from xgboost import XGBClassifier

XG_model=XGBClassifier( n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    eval_metric="logloss") # for now basic parameter for comparison
XG_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [25]:
XG_prediction= XG_model.predict(X_test)
XG_probabilities=XG_model.predict_proba(X_test)[:,1]

In [26]:
#Evaluating Models
#check accuracy 
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score


def fraud_metrics(y_test,y_predict):
    return{                                       # return dictionary with all values
    "accuracy":accuracy_score(y_test,y_predict),
    "precision":precision_score(y_test,y_predict),
    "recall":recall_score(y_test,y_predict),
    "f1":f1_score(y_test,y_predict),
    }

In [27]:
#Logistic Regresson Evaluation  
LR_evaluate=fraud_metrics(y_test,LR_prediction)


#Random Forest EValuation
RF_evaluate=fraud_metrics(y_test,RF_prediction)

#XG Boost Evaluation
XG_evaluate= fraud_metrics(y_test,XG_prediction)

In [28]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, RF_prediction)

print(cm)

[[56856     8]
 [   21    77]]

In [29]:
#Put evrything in a table
# print result:
results = pd.DataFrame([                                    #pd.Dataframe() for table representation of dict
    {"Model": "Logistic Regression", **LR_evaluate},       #** for unpacking dictionary
    {"Model": "Decision Tree", **RF_evaluate},
    {"Model": "Random Forest", **XG_evaluate}
])

print(results)

                 Model  accuracy  precision    recall        f1
0  Logistic Regression  0.973860   0.057288  0.918367  0.107849
1        Decision Tree  0.999491   0.905882  0.785714  0.841530
2        Random Forest  0.999491   0.896552  0.795918  0.843243

In [30]:
#calculate PR AUC score
from sklearn.metrics import average_precision_score

logistic_PR_AUC=average_precision_score(y_test,LR_Probabilites)
Random_Forest_PR_AUC=average_precision_score(y_test,RF_probabilities)
XGB_PR_AUC=average_precision_score(y_test,XG_probabilities)
results["PR_AUC"]=[logistic_PR_AUC,Random_Forest_PR_AUC,XGB_PR_AUC]
print(results)

                 Model  accuracy  precision    recall        f1    PR_AUC
0  Logistic Regression  0.973860   0.057288  0.918367  0.107849  0.717527
1        Decision Tree  0.999491   0.905882  0.785714  0.841530  0.862940
2        Random Forest  0.999491   0.896552  0.795918  0.843243  0.834176

In [31]:
#Understanding threshold andhow it affects my model
from sklearn.metrics import f1_score, precision_score, recall_score

thresholds = [0.2, 0.3, 0.4, 0.5, 0.6, 0.7]

for threshold in thresholds:

    predictions = (XG_probabilities >= threshold).astype(int)

    precision = precision_score(y_test, predictions)
    recall = recall_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)

    print(
        f"Threshold: {threshold:.1f} | "
        f"Precision: {precision:.3f} | "
        f"Recall: {recall:.3f} | "
        f"F1: {f1:.3f}"
    )

Threshold: 0.2 | Precision: 0.876 | Recall: 0.796 | F1: 0.834
Threshold: 0.3 | Precision: 0.897 | Recall: 0.796 | F1: 0.843
Threshold: 0.4 | Precision: 0.897 | Recall: 0.796 | F1: 0.843
Threshold: 0.5 | Precision: 0.897 | Recall: 0.796 | F1: 0.843
Threshold: 0.6 | Precision: 0.928 | Recall: 0.786 | F1: 0.851
Threshold: 0.7 | Precision: 0.938 | Recall: 0.776 | F1: 0.849

ML FLOW EXPERIMENT TRACKING

In [32]:
import mlflow
import mlflow.sklearn

mlflow.set_experiment("Fraud Detection")
print("MLflow experiment configured.")

MLflow experiment configured.

In [33]:
#Track Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    average_precision_score,
    f1_score,
    precision_score,
    recall_score,
)

with mlflow.start_run(run_name="Logistic Regression"):

    # 1.Parameters
    params={
        "model_type":"Logistic Regression",
        "class_weight" : "balanced",
        "max_iter":1000,
        "random_state":42
    }
    mlflow.log_params(params)
        
    
    
    #2. Train model
    model = LogisticRegression(
            class_weight="balanced",
            max_iter=1000,
            random_state=42
        )
    model.fit(X_train, y_train)

    #3. Predictions
    predictions=model.predict(X_test)
    probabilities=model.predict_proba(X_test)[:,1]

    #4. Metrics
    precision=precision_score(y_test,predictions)
    recall=recall_score(y_test,predictions)
    f1=f1_score(y_test,predictions)
    pr_auc=average_precision_score(y_test,probabilities)

    mlflow.log_metrics({
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "pr_auc": pr_auc
    })

    #5. Log model
    model_info=mlflow.sklearn.log_model(
        sk_model=model,
        name="Logistic_regression_model"
    )

    #6. Tag
    mlflow.set_tag(
        "model_description",
        "Baseline fraud detection logistic Regression"
    )
    print("Logistic Regression tracked successfully.")
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1:", f1)
    print("PR-AUC:", pr_auc)

C:\Users\Admin\OneDrive\Desktop\ML_OPS_FRAUD_DETECTION_project 3\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression tracked successfully.
Precision: 0.05728835136855506
Recall: 0.9183673469387755
F1: 0.10784901138406232
PR-AUC: 0.7175274015818162

In [43]:
from sklearn.ensemble import RandomForestClassifier

with mlflow.start_run(run_name="Random Forest"):

    # -------------------------
    # Parameters
    # -------------------------
    params = {
        "model_type": "Random Forest",
        "n_estimators": 100,
        "class_weight": "balanced",
        "random_state": 42,
        "n_jobs": -1
    }

    mlflow.log_params(params)

    # -------------------------
    # Train
    # -------------------------
    model = RandomForestClassifier(
        n_estimators=100,
        class_weight="balanced",
        random_state=42,
        n_jobs=-1
    )

    model.fit(X_train, y_train)

    # -------------------------
    # Predictions
    # -------------------------
    predictions = model.predict(X_test)
    probabilities = model.predict_proba(X_test)[:, 1]

    # -------------------------
    # Metrics
    # -------------------------
    precision = precision_score(y_test, predictions)
    recall = recall_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)
    pr_auc = average_precision_score(y_test, probabilities)

    mlflow.log_metrics({
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "pr_auc": pr_auc
    })

    # -------------------------
    # Model
    # -------------------------
    model_info = mlflow.sklearn.log_model(
        sk_model=model,
        name="random_forest_model",
        skops_trusted_types=["sklearn.tree._tree.Tree"]
    )

    mlflow.set_tag(
        "model_description",
        "Random Forest fraud detection model"
    )

    print("Random Forest tracked successfully.")
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1:", f1)
    print("PR-AUC:", pr_auc)

Random Forest tracked successfully.
Precision: 0.9058823529411765
Recall: 0.7857142857142857
F1: 0.8415300546448088
PR-AUC: 0.862939836265611

In [46]:
from xgboost import XGBClassifier

with mlflow.start_run(run_name="XGBoost"):

    # -------------------------
    # Parameters
    # -------------------------
    params = {
        "model_type": "XGBoost",
        "n_estimators": 100,
        "max_depth": 6,
        "learning_rate": 0.1,
        "random_state": 42,
        "eval_metric": "logloss"
    }

    mlflow.log_params(params)

    # -------------------------
    # Train
    # -------------------------
    model = XGBClassifier(
        n_estimators=100,
        max_depth=6,
        learning_rate=0.1,
        random_state=42,
        eval_metric="logloss"
    )

    model.fit(X_train, y_train)

    # -------------------------
    # Predictions
    # -------------------------
    predictions = model.predict(X_test)
    probabilities = model.predict_proba(X_test)[:, 1]

    # -------------------------
    # Metrics
    # -------------------------
    precision = precision_score(y_test, predictions)
    recall = recall_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)
    pr_auc = average_precision_score(y_test, probabilities)

    mlflow.log_metrics({
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "pr_auc": pr_auc
    })

    # -------------------------
    # Model
    # -------------------------
    model_info = mlflow.xgboost.log_model(
        xgb_model=model,
        name="xgboost_model"
    )

    # -------------------------
    # Tag
    # -------------------------
    mlflow.set_tag(
        "model_description",
        "XGBoost fraud detection model"
    )

    print("XGBoost tracked successfully.")
    print("Precision:", precision)
    print("Recall:", recall)
    print("F1:", f1)
    print("PR-AUC:", pr_auc)

XGBoost tracked successfully.
Precision: 0.896551724137931
Recall: 0.7959183673469388
F1: 0.8432432432432433
PR-AUC: 0.8341761558727578

In [2]:
import mlflow

print("Tracking URI:")
print(mlflow.get_tracking_uri())

print("\nExperiment:")
experiment = mlflow.get_experiment_by_name("Fraud Detection")
print(experiment)

c:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Tracking URI:
sqlite:///C:/Users/Admin/OneDrive/Desktop/ML_OPS_FRAUD_DETECTION_project%203/notebooks/mlflow.db

Experiment:
<Experiment: artifact_location=('file:///C:/Users/Admin/OneDrive/Desktop/ML_OPS_FRAUD_DETECTION_project '
 '3/notebooks/mlruns/1'), creation_time=1789922637919, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1789922637919, lifecycle_stage='active', name='Fraud Detection', tags={}, trace_location=None, workspace='default'>

In [3]:
runs = mlflow.search_runs(
    experiment_names=["Fraud Detection"]
)

runs[[
    "run_id",
    "status",
    "tags.mlflow.runName"
]]

                             run_id    status  tags.mlflow.runName
0  c5bb92aad1d241189d60bc603451fe4b  FINISHED              XGBoost
1  55f427336c884ef8846525696cd12490    FAILED              XGBoost
2  976633e1c5494ba18b3c83e9b10a598c    FAILED              XGBoost
3  8c4faf88525c41e09955bed4093187b9  FINISHED        Random Forest
4  554b66acf21f41ab8e429ae0e8b784ce    FAILED        Random Forest
5  a24f0669c8e64c84b90908886ff411b0    FAILED              XGBoost
6  3ccb2cd99cf14e089e1b79cceff8896f    FAILED              XGBoost
7  fb51a652a02d484d97415cb54ad9564f  FINISHED  Logistic Regression
8  e04f8507f6d74cafa31ff68cf30b3f27    FAILED  Logistic Regression
9  326ff28deb064ab5a03c3c15637fbe3f    FAILED  Logistic Regression

In [4]:
import mlflow

mlflow.set_tracking_uri(
    "sqlite:///C:/Users/Admin/OneDrive/Desktop/ML_OPS_FRAUD_DETECTION_project%203/notebooks/mlflow.db"
)

print(mlflow.get_tracking_uri())

sqlite:///C:/Users/Admin/OneDrive/Desktop/ML_OPS_FRAUD_DETECTION_project%203/notebooks/mlflow.db

In [5]:
print(mlflow.get_experiment_by_name("Fraud Detection"))

<Experiment: artifact_location=('file:///C:/Users/Admin/OneDrive/Desktop/ML_OPS_FRAUD_DETECTION_project '
 '3/notebooks/mlruns/1'), creation_time=1789922637919, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1789922637919, lifecycle_stage='active', name='Fraud Detection', tags={}, trace_location=None, workspace='default'>

In [6]:
mlflow.set_experiment("Fraud Detection")

<Experiment: artifact_location=('file:///C:/Users/Admin/OneDrive/Desktop/ML_OPS_FRAUD_DETECTION_project '
 '3/notebooks/mlruns/1'), creation_time=1789922637919, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1789922637919, lifecycle_stage='active', name='Fraud Detection', tags={}, trace_location=None, workspace='default'>

In [7]:
experiment = mlflow.get_experiment_by_name("Fraud Detection")

print(experiment.name)
print(experiment.experiment_id)

Fraud Detection
1

In [1]:
import mlflow

mlflow.set_tracking_uri("http://127.0.0.1:5000")
print(mlflow.get_tracking_uri())

c:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

http://127.0.0.1:5000

In [9]:
#Findinf my runs
runs=mlflow.search_runs(experiment_names =["Fraud Detection"])
runs[[
    "run_id",
    "status",
    "tags.mlflow.runName"
]]

                             run_id    status  tags.mlflow.runName
0  c5bb92aad1d241189d60bc603451fe4b  FINISHED              XGBoost
1  55f427336c884ef8846525696cd12490    FAILED              XGBoost
2  976633e1c5494ba18b3c83e9b10a598c    FAILED              XGBoost
3  8c4faf88525c41e09955bed4093187b9  FINISHED        Random Forest
4  554b66acf21f41ab8e429ae0e8b784ce    FAILED        Random Forest
5  a24f0669c8e64c84b90908886ff411b0    FAILED              XGBoost
6  3ccb2cd99cf14e089e1b79cceff8896f    FAILED              XGBoost
7  fb51a652a02d484d97415cb54ad9564f  FINISHED  Logistic Regression
8  e04f8507f6d74cafa31ff68cf30b3f27    FAILED  Logistic Regression
9  326ff28deb064ab5a03c3c15637fbe3f    FAILED  Logistic Regression

In [10]:
#Create the XGBoost model URI
model_uri="runs:/c5bb92aad1d241189d60bc603451fe4b/xgboost_model"
model_uri

'runs:/c5bb92aad1d241189d60bc603451fe4b/xgboost_model'

In [11]:
#load the model
loaded_model=mlflow.xgboost.load_model(model_uri)
print("Model Loaded Sucessfully")

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
Downloading artifacts: 100%|██████████| 5/5 [00:00<00:00, 14.58it/s]

Model Loaded Sucessfully

In [28]:
#Using 5 transactions from X_test for checking the loaded model
sample=X_test.iloc[:5]
predictions=loaded_model.predict(sample)
predictions

array([0, 0, 0, 0, 0])

In [30]:
probabilities=loaded_model.predict_proba(sample)[:,1]
probabilities

array([6.5804848e-06, 9.7526017e-06, 2.2444996e-04, 2.9054663e-06,
       7.1831926e-04], dtype=float32)

In [47]:
for probability in probabilities:
    if probability >= 0.5:
        Risk= "High"
    else:
        Risk="low"
    
    print(
        f"Fraud probability: {probability:.6f}  "  f"({probability * 100:.4f}%)  | Risk: {Risk}"
    )

Fraud probability: 0.000007  (0.0007%)  | Risk: low
Fraud probability: 0.000010  (0.0010%)  | Risk: low
Fraud probability: 0.000224  (0.0224%)  | Risk: low
Fraud probability: 0.000003  (0.0003%)  | Risk: low
Fraud probability: 0.000718  (0.0718%)  | Risk: low

In [48]:
#testingfor actual fraud if any
import numpy as np

print("Actual labels:")
print(y_test.iloc[:5].values)

print("\nPredicted probabilities:")
print(probabilities)

Actual labels:
[0 0 0 0 0]

Predicted probabilities:
[6.5804848e-06 9.7526017e-06 2.2444996e-04 2.9054663e-06 7.1831926e-04]

In [49]:
fraud_indices = np.where(y_test.values == 1)[0]

print("Number of fraud transactions in test set:", len(fraud_indices))
print("First 5 fraud indices:", fraud_indices[:5])

Number of fraud transactions in test set: 98
First 5 fraud indices: [ 840 1146 3287 4276 5077]

In [15]:
sample_transaction = X_test.iloc[0]

sample_transaction

Time      160760.000000
V1            -0.674466
V2             1.408105
V3            -1.110622
V4            -1.328366
V5             1.388996
V6            -1.308439
V7             1.885879
V8            -0.614233
V9             0.311652
V10            0.650757
V11           -0.857785
V12           -0.229961
V13           -0.199817
V14            0.266371
V15           -0.046544
V16           -0.741398
V17           -0.605617
V18           -0.392568
V19           -0.162648
V20            0.394322
V21            0.080084
V22            0.810034
V23           -0.224327
V24            0.707899
V25           -0.135837
V26            0.045102
V27            0.533837
V28            0.291319
Amount        23.000000
Name: 263020, dtype: float64

In [16]:
sample_json = sample_transaction.to_dict()

sample_json

{'Time': 160760.0,
 'V1': -0.674466064578314,
 'V2': 1.40810501967799,
 'V3': -1.11062205357093,
 'V4': -1.32836577843066,
 'V5': 1.38899603254837,
 'V6': -1.30843906707795,
 'V7': 1.88587890268717,
 'V8': -0.614232966299775,
 'V9': 0.311652212453101,
 'V10': 0.65075700363522,
 'V11': -0.857784661547805,
 'V12': -0.229961445775592,
 'V13': -0.19981700479103,
 'V14': 0.266371326329879,
 'V15': -0.0465441684754424,
 'V16': -0.741398089749789,
 'V17': -0.605616644106022,
 'V18': -0.39256818789208,
 'V19': -0.162648311024695,
 'V20': 0.394321820843914,
 'V21': 0.0800842396026648,
 'V22': 0.810033595602455,
 'V23': -0.224327230436412,
 'V24': 0.707899237446867,
 'V25': -0.13583702273753,
 'V26': 0.0451021964988772,
 'V27': 0.533837219064273,
 'V28': 0.291319252625364,
 'Amount': 23.0}

In [3]:
xgb_run_id = "c5bb92aad1d241189d60bc603451fe4b"

model_uri = f"runs:/{xgb_run_id}/xgboost_model"

print(model_uri)

runs:/c5bb92aad1d241189d60bc603451fe4b/xgboost_model

In [4]:
loaded_model = mlflow.xgboost.load_model(model_uri)

print("MODEL LOADED SUCCESSFULLY")

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
Downloading artifacts: 100%|██████████| 5/5 [00:00<00:00, 20.48it/s]

MODEL LOADED SUCCESSFULLY

In [5]:
model_uri = "runs:/c5bb92aad1d241189d60bc603451fe4b/xgboost_model"

print(model_uri)

runs:/c5bb92aad1d241189d60bc603451fe4b/xgboost_model

In [6]:
loaded_model = mlflow.xgboost.load_model(model_uri)

print("MODEL LOADED SUCCESSFULLY!")

Downloading artifacts:   0%|          | 0/1 [00:00<?, ?it/s]
Downloading artifacts: 100%|██████████| 5/5 [00:00<00:00, 658.82it/s]

MODEL LOADED SUCCESSFULLY!

In [22]:
sample_transaction_2 = X_test.iloc[1]

sample_transaction_2.to_dict()

{'Time': 19847.0,
 'V1': -2.82981594327279,
 'V2': -2.76514921229269,
 'V3': 2.53779295063997,
 'V4': -1.07458042259191,
 'V5': 2.84255889292598,
 'V6': -2.15353644367205,
 'V7': -1.79551885720369,
 'V8': -0.250020372324704,
 'V9': 3.07350426338358,
 'V10': -1.00041794567463,
 'V11': 1.85084176033081,
 'V12': -1.54977887088034,
 'V13': 1.25233673695303,
 'V14': 0.963974373307274,
 'V15': -0.481027223791626,
 'V16': -0.14731917203129,
 'V17': -0.209328171581066,
 'V18': 1.05889790297841,
 'V19': 0.397056508186649,
 'V20': -0.515764693656115,
 'V21': -0.295554564490287,
 'V22': 0.109304966698836,
 'V23': -0.81327196874425,
 'V24': 0.0429955726118499,
 'V25': -0.0276596849389052,
 'V26': -0.910247054904536,
 'V27': 0.110801759066737,
 'V28': -0.511938134872381,
 'Amount': 11.85}